In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## **ORDERS**

In [2]:
orders = pd.read_csv(r"C:\Users\Atharva\Downloads\College Project by Ruchi Mam\orders - orders.csv")
orders.head(10)

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,20,20.0,1,1,49.990000,19.49
1,2,2012-03-19 19:27:37,104,104.0,1,1,49.990000,19.49
2,3,2012-03-20 6:44:45,147,147.0,1,1,49.990000,19.49
3,4,2012-03-20 9:41:45,160,160.0,1,1,49.990000,19.49
4,5,2012-03-20 11:28:15,177,177.0,1,1,49.990000,19.49
5,6,2012-03-20 16:12:47,232,232.0,1,1,51.977855,19.49
6,7,2012-03-20 17:03:41,241,241.0,1,1,49.990000,19.49
7,8,2012-03-20 23:35:27,295,295.0,1,1,49.990000,19.49
8,9,2012-03-21 2:35:01,304,304.0,1,1,49.990000,19.49
9,10,2012-03-21 6:45:58,317,317.0,1,1,49.990000,19.49

In [4]:
orders.shape

(32313, 8)

In [6]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32313 entries, 0 to 32312
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            32313 non-null  int64
 1   created_at          32313 non-null  object
 2   website_session_id  32313 non-null  int64
 3   user_id             30697 non-null  float64
 4   primary_product_id  32313 non-null  int64
 5   items_purchased     32313 non-null  int64
 6   price_usd           32313 non-null  float64
 7   cogs_usd            32313 non-null  float64
dtypes: float64(3), int64(4), object(1)
memory usage: 2.0+ MB

In [5]:
orders.describe()

,order_id,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
count,32313.000000,32313.000000,30697.000000,32313.000000,32313.000000,32313.000000,32313.000000
mean,16157.000000,258292.288707,215452.840799,1.392474,1.238666,60.183380,22.355406
std,9328.103961,132427.649842,108505.252060,0.732277,0.426274,17.882265,6.238621
min,1.000000,20.000000,13.000000,1.000000,1.000000,29.990000,9.490000
25%,8079.000000,144828.000000,123767.000000,1.000000,1.000000,49.990000,19.490000
50%,16157.000000,263554.000000,221134.000000,1.000000,1.000000,49.990000,19.490000
75%,24235.000000,374799.000000,310542.000000,2.000000,1.000000,59.990000,22.490000
max,32313.000000,472818.000000,394273.000000,4.000000,2.000000,114.353361,41.980000

In [13]:
orders.dtypes

order_id                int64
created_at             object
website_session_id      int64
user_id               float64
primary_product_id      int64
items_purchased         int64
price_usd             float64
cogs_usd              float64
dtype: object

In [12]:
orders.isnull().sum()

order_id                 0
created_at               0
website_session_id       0
user_id               1616
primary_product_id       0
items_purchased          0
price_usd                0
cogs_usd                 0
dtype: int64

In [14]:
orders["user_id"] = orders["user_id"].fillna(0).astype(int)

In [15]:
orders.isnull().sum()

order_id              0
created_at            0
website_session_id    0
user_id               0
primary_product_id    0
items_purchased       0
price_usd             0
cogs_usd              0
dtype: int64

In [16]:
orders.duplicated().sum()

np.int64(0)

In [17]:
orders["created_at"] = pd.to_datetime(orders["created_at"])

## **ORDER ITEMS**

In [18]:
order_items = pd.read_csv(r"C:\Users\Atharva\Downloads\College Project by Ruchi Mam\order_items - order_items.csv")
order_items.head(5)

,order_item_id,created_at,order_id,product_id,is_primary_item,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,1,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,2,1,1,49.99,19.49
2,3,2012-03-20 6:44:45,3,1,1,49.99,19.49
3,4,2012-03-20 9:41:45,4,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,5,1,1,49.99,19.49

In [19]:
order_items.shape

(40025, 7)

In [21]:
order_items.dtypes

order_item_id        int64
created_at          object
order_id             int64
product_id           int64
is_primary_item      int64
price_usd          float64
cogs_usd           float64
dtype: object

In [25]:
order_items.describe()

,order_item_id,created_at,order_id,product_id,is_primary_item,price_usd,cogs_usd
count,40025.000000,40025,40025.000000,40025.000000,40025.000000,40025.000000,40025.000000
mean,20013.000000,2014-05-13 10:24:45.947732736,17121.957502,1.770019,0.807320,48.432473,18.047976
min,1.000000,2012-03-19 10:42:46,1.000000,1.000000,0.000000,29.990000,9.490000
25%,10007.000000,2013-12-25 23:27:19,9871.000000,1.000000,1.000000,49.990000,19.490000
50%,20013.000000,2014-07-14 15:31:31,17490.000000,1.000000,1.000000,49.990000,19.490000
75%,30019.000000,2014-12-01 16:41:10,24818.000000,2.000000,1.000000,49.990000,19.490000
max,40025.000000,2015-03-19 05:38:31,32313.000000,4.000000,1.000000,59.990000,22.490000
std,11554.366599,NaN,9053.765867,1.085561,0.394408,8.012370,3.856821

In [22]:
order_items["created_at"] = pd.to_datetime(order_items["created_at"])

In [23]:
order_items.isnull().sum()

order_item_id      0
created_at         0
order_id           0
product_id         0
is_primary_item    0
price_usd          0
cogs_usd           0
dtype: int64

In [24]:
order_items.duplicated().sum()

np.int64(0)

## **PRODUCTS**

In [26]:
products = pd.read_csv(r"C:\Users\Atharva\Downloads\College Project by Ruchi Mam\products - products (1).csv")
products.head(10)

   product_id           created_at                 product_name
0           1   2012-03-19 8:00:00       The Original Mr. Fuzzy
1           2  2013-01-06 13:00:00        The Forever Love Bear
2           3   2013-12-12 9:00:00  The Birthday Sugar Panda-v2
3           4  2014-02-05 10:00:00   The Hudson River Mini bear

In [27]:
products.dtypes

product_id       int64
created_at      object
product_name    object
dtype: object

In [28]:
products["created_at"] = pd.to_datetime(products["created_at"])

## **REFUNDS**

In [29]:
refunds = pd.read_csv(r"C:\Users\Atharva\Downloads\College Project by Ruchi Mam\order_item_refunds - order_item_refunds.csv")
refunds.head(10)

,order_item_refund_id,created_at,order_item_id,order_id,refund_amount_usd
0,1,2012-04-06 11:32:43,57,57,49.99
1,2,2012-04-13 1:09:43,74,74,49.99
2,3,2012-04-15 7:03:48,71,71,49.99
3,4,2012-04-17 20:00:37,118,118,49.99
4,5,2012-04-22 20:53:49,116,116,49.99
5,6,2012-05-04 11:59:07,147,147,49.99
6,7,2012-05-12 2:41:14,186,186,49.99
7,8,2012-05-16 13:06:01,191,191,49.99
8,9,2012-05-24 16:00:09,179,179,49.99
9,10,2012-05-30 17:20:44,199,199,49.99

In [31]:
refunds.shape

(1731, 5)

In [32]:
refunds.dtypes

order_item_refund_id      int64
created_at               object
order_item_id             int64
order_id                  int64
refund_amount_usd       float64
dtype: object

In [33]:
refunds.describe()

       order_item_refund_id  order_item_id      order_id  refund_amount_usd
count           1731.000000    1731.000000   1731.000000        1731.000000
mean             866.000000   18472.214905  15868.242057          49.300225
std              499.840975   11438.074606   9096.061945           4.956015
min                1.000000      57.000000     57.000000          29.990000
25%              433.500000    7417.000000   7412.000000          49.990000
50%              866.000000   19858.000000  17375.000000          49.990000
75%             1298.500000   26900.000000  22539.500000          49.990000
max             1731.000000   39950.000000  32255.000000          59.990000

In [34]:
refunds.isnull().sum()

order_item_refund_id    0
created_at              0
order_item_id           0
order_id                0
refund_amount_usd       0
dtype: int64

In [35]:
refunds.duplicated().sum()

np.int64(0)

In [44]:
refunds["created_at"] = pd.to_datetime(refunds["created_at"])

## **PAGEVIEWS**

In [45]:
web_pageviews = pd.read_csv(r"C:\Users\Atharva\Downloads\College Project by Ruchi Mam\website_pageviews - website_pageviews.csv")
web_pageviews.head(5)

   website_pageview_id          created_at  website_session_id pageview_url
0                    1  2012-03-19 8:04:16                   1        /home
1                    2  2012-03-19 8:16:49                   2        /home
2                    3  2012-03-19 8:26:55                   3        /home
3                    4  2012-03-19 8:37:33                   4        /home
4                    5  2012-03-19 9:00:55                   5        /home

In [46]:
web_pageviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1188124 entries, 0 to 1188123
Data columns (total 4 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   website_pageview_id  1188124 non-null  int64
 1   created_at           1188124 non-null  object
 2   website_session_id   1188124 non-null  int64
 3   pageview_url         1188124 non-null  object
dtypes: int64(2), object(2)
memory usage: 36.3+ MB

In [47]:
web_pageviews.isnull().sum()

website_pageview_id    0
created_at             0
website_session_id     0
pageview_url           0
dtype: int64

In [48]:
web_pageviews.duplicated().sum()

np.int64(0)

In [49]:
web_pageviews.dtypes

website_pageview_id     int64
created_at             object
website_session_id      int64
pageview_url           object
dtype: object

In [63]:
web_pageviews["created_at"] = pd.to_datetime(web_pageviews["created_at"])

In [64]:
web_pageviews.dtypes

website_pageview_id             int64
created_at             datetime64[ns]
website_session_id              int64
pageview_url                   object
created_at             datetime64[ns]
dtype: object

In [65]:
web_pageviews.columns

Index(['website_pageview_id', 'created_at', 'website_session_id',
       'pageview_url', 'created_at '],
      dtype='object')

In [66]:
web_pageviews = web_pageviews.drop(columns=['created_at '])

In [67]:
web_pageviews.columns

Index(['website_pageview_id', 'created_at', 'website_session_id',
       'pageview_url'],
      dtype='object')

In [68]:
web_pageviews.dtypes

website_pageview_id             int64
created_at             datetime64[ns]
website_session_id              int64
pageview_url                   object
dtype: object

## **SESSIONS**

In [2]:
web_sessions = pd.read_csv(r"C:\Users\Atharva\Downloads\College Project by Ruchi Mam\website_sessions - website_sessions.csv")
web_sessions.head(50)

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,2012-03-19 8:04:16,1,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
1,2,2012-03-19 8:16:49,2,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,2012-03-19 8:26:55,3,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
3,4,2012-03-19 8:37:33,4,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
4,5,2012-03-19 9:00:55,5,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
5,6,2012-03-19 9:05:46,6,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
6,7,2012-03-19 9:06:27,7,0,Gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
7,8,2012-03-19 9:17:17,8,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
8,9,2012-03-19 9:27:56,9,0,gsearch,NaN,g_ad_1,mobile,https://www.gsearch.com
9,10,2012-03-19 9:35:37,10,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
10,11,2012-03-19 9:37:42,11,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
11,12,2012-03-19 9:39:57,12,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
12,13,2012-03-19 9:45:29,13,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
13,14,2012-03-19 9:45:47,14,0,gsearch,NaN,g_ad_1,mobile,https://www.gsearch.com
14,15,2012-03-19 9:57:14,15,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
15,16,2012-03-19 10:01:35,16,0,gsearch,NaN,g_ad_1,mobile,https://www.gsearch.com
16,17,2012-03-19 10:14:34,17,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
17,18,2012-03-19 10:16:57,18,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
18,19,2012-03-19 10:17:38,19,0,gsearch,NaN,g_ad_1,mobile,https://www.gsearch.com
19,20,2012-03-19 10:22:58,20,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
20,21,2012-03-19 10:51:38,21,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
21,22,2012-03-19 10:54:55,22,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
22,23,2012-03-19 10:59:03,23,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
23,24,2012-03-19 11:08:58,24,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
24,25,2012-03-19 11:16:42,25,0,GSEARCH,NaN,g_ad_1,desktop,https://www.gsearch.com
25,26,2012-03-19 11:20:14,26,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
26,27,2012-03-19 11:22:58,27,0,Gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
27,28,2012-03-19 11:24:59,28,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
28,29,2012-03-19 11:33:47,29,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
29,30,2012-03-19 11:43:21,30,0,gsearch,NaN,g_ad_1,desktop,https://www.gsearch.com
30,31,2012-03-19 11:46:37,31,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
31,32,2012-03-19 11:53:24,32,0,gsearch_ads,nonbrand,g_ad_1,mobile,https://www.gsearch.com
32,33,2012-03-19 11:58:52,33,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
33,34,2012-03-19 12:01:28,34,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
34,35,2012-03-19 12:02:18,35,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
35,36,2012-03-19 12:07:36,36,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
36,37,2012-03-19 12:09:24,37,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
37,38,2012-03-19 12:23:11,38,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
38,39,2012-03-19 12:35:54,39,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
39,40,2012-03-19 12:45:10,40,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
40,41,2012-03-19 12:55:38,41,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
41,42,2012-03-19 12:55:57,42,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
42,43,2012-03-19 12:57:35,43,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
43,44,2012-03-19 13:10:20,44,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
44,45,2012-03-19 13:11:43,45,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
45,46,2012-03-19 13:14:49,46,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
46,47,2012-03-19 13:19:35,47,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
47,48,2012-03-19 13:25:51,48,0,gsearch,NaN,g_ad_1,desktop,https://www.gsearch.com
48,49,2012-03-19 13:29:52,49,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
49,50,2012-03-19 13:30:31,50,0,gsearch,NaN,g_ad_1,desktop,https://www.gsearch.com

In [3]:
web_sessions.shape

(482328, 9)

In [4]:
web_sessions.dtypes

website_session_id     int64
created_at            object
user_id                int64
is_repeat_session      int64
utm_source            object
utm_campaign          object
utm_content           object
device_type           object
http_referer          object
dtype: object

In [5]:
web_sessions["created_at"] = pd.to_datetime(web_sessions["created_at"])

In [6]:
web_sessions.dtypes

website_session_id             int64
created_at            datetime64[ns]
user_id                        int64
is_repeat_session              int64
utm_source                    object
utm_campaign                  object
utm_content                   object
device_type                   object
http_referer                  object
dtype: object

In [7]:
web_sessions.isnull().sum()

website_session_id         0
created_at                 0
user_id                    0
is_repeat_session          0
utm_source             75560
utm_campaign          132617
utm_content            84981
device_type                0
http_referer           40724
dtype: int64

In [8]:
web_sessions.duplicated().sum()

np.int64(9457)

In [77]:

web_sessions["created_at"] = pd.to_datetime(web_sessions["created_at"])
print(web_sessions.dtypes)

website_session_id             int64
created_at            datetime64[ns]
user_id                        int64
is_repeat_session              int64
utm_source                    object
utm_campaign                  object
utm_content                   object
device_type                   object
http_referer                  object
dtype: object

In [80]:
orphaned_pageviews = web_pageviews[~web_pageviews['website_session_id'].isin(web_sessions['website_session_id'])]

print("--- Cross-Table Integrity Check ---")
print(f"Number of orphaned pageview rows: {len(orphaned_pageviews)}")

--- Cross-Table Integrity Check ---
Number of orphaned pageview rows: 0

In [83]:
# Check if there are any refunds pointing to a non-existent order
orphaned_refunds = refunds[~refunds["order_id"].isin(orders["order_id"])]

print("--- Cross-Table Integrity Check ---")
print(f"Number of orphaned refunds rows: {len(orphaned_refunds)}")

--- Cross-Table Integrity Check ---
Number of orphaned refunds rows: 0

## **EXPORTING THE CSV FILES**

In [88]:
orders.to_csv("orders_clean.csv" , index = False)

In [89]:
web_pageviews.to_csv("web_pageviews_clean.csv" , index = False)
order_items.to_csv("order_items_clean.csv" , index = False)
products.to_csv("products_clean.csv" , index = False)
refunds.to_csv("refunds_clean.csv" , index = False)
web_sessions.to_csv("web_sessions_clean.csv" , index = False)

In [90]:
import os

In [91]:
os.getcwd()

'C:\\Users\\Atharva'